method: MeanShift
kernel: gaussian
iterations: 50
keops: True
blurring: True
bandwidths:
  - 0.01
  - 0.02
  - 0.03
  - 0.04
  - 0.05
  - 0.06
  - 0.07
  - 0.08
  - 0.09
  - 0.1
  - 0.11
  - 0.12
  - 0.13
  - 0.14
  - 0.15
  - 0.16
  - 0.17
  - 0.18
  - 0.19
  - 0.2
  - 0.21
  - 0.22
  - 0.23
  - 0.24
  - 0.25
  - 0.26
  - 0.27
  - 0.28
  - 0.29
  - 0.3
thresholds:
  - 0.2
  - 0.1
  - 0.04
  - 0.02
  - 0.01
  - 0.001
  - same
  # uncomment for ISBI
  # - 2.0
  # - 1.0
  # - 0.5