method: KL
graph_type: complete  # type of graph used: "complete" or "offset"
pool_executor: thread  # parallelise over images using "thread", "process", "sequential"
repeats: 3  # number of runs
downsample_factor: 8  # downsample factor for the images
timed: True  # should the runtimes be measured