method: "HDBSCAN"
min_samples:
  - 1
  - 2
  - 5
  - 10
  - 20
  - 50
  - 100
  - same
min_cluster_sizes:
  - 2
  - 5
  - 10
  - 20
  - 50
  - 100
  - 150
  - 200
  - 250
  - 300
  - 350
  - 400
  - 450
  - 500
  - 550
  - 600
