name: ModShift
channels:
  - pytorch
  - anaconda
  - abailoni
  - conda-forge
  - defaults
dependencies:
  - affogato=0.1.glia
  - cudatoolkit=10.0.130
  - h5py=2.9.0
  - hdbscan=0.8.23
  - hdf5=1.10.4
  - joblib=0.17.0
  - matplotlib=3.1.1
  - nifty=1.0.7
  - numpy=1.17.2
  - pip=19.2.3
  - python=3.7.4
  - pytorch=1.2.0
  - pyyaml=5.1.2
  - requests=2.22.0
  - scikit-image=0.16.2
  - scikit-learn=0.21.3
  - scipy=1.1.0
  - tqdm=4.38.0
  - yaml=0.1.7
  - pip:
    - fastcluster==1.1.25
    - pykeops==1.2
    - ray==1.0.1.post1

