data:
  dataset: 3clusters
  downsample_factor: 1
  root_path: ./data/

ModShift:
  keops: False # use keops or not
  save_all: True # save full trajectory or only initial and final locations
  optimization:
    batch_size: 1
    blurring: false # use blurring or non-blurring Mod Shift
    compute_gradients_early: False # compute gradients early if computational graph does not fit on GPU
    iterations: 30
    optimizer:
      learning_rate: 0.01
      type: SGD
      momentum: 0.0
    scheduler: # reduces the learning rate after ratio of the total number of iterations by gamma
      gamma: 0.1
      ratio: 0.85
    subsample_size: 12288 # size of subsample that is processed at the same time on GPU, set such that GPU memory is fully used
  rho:
    type: clipped_linear
  torch:
    device: cuda
  weight_func:
    beta: 0.7 # beta value of Mod Shift
    type: clipped_linear